name: Publish Docker Images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  docker-publish:
    name: Build and Push CPU & CUDA Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [cpu, cuda]

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧱 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏷 Extract version (strip leading 'v')
        id: extract
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
      
      - name: 🐳 Build and Push ${{ matrix.variant }} Image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile.${{ matrix.variant }}
          push: true
          tags: |
            voxextractlabs/vox-whisper:${{ matrix.variant }}-latest
            voxextractlabs/vox-whisper:${{ matrix.variant }}-v${{ steps.extract.outputs.version }}
